### ISSUE TITLE
Upgrade Python used

### ISSUE THREAD

**Issue by TheLastProject** [Pext/Pext#457]
Pext binaries currently use Python 3.6, which requests dropped (see #455).

It needs to be upgraded to a newer Python and the AppImage build needs to be fixed.

**Comment by TheLastProject** [comment]
In #483 it was found out that pep257 is no longer maintained and incompatible with Python 3.10. We should switch to its successor pydocstyle so we can upgrade Python to a newer release.

**Comment by airvzxf** [comment]
Only to be clear, the actual scope for this issue is moved the pep257 to pydocstyle. Is this all?

**Comment by TheLastProject** [comment]
The scope is to update the Python version (without increasing the Ubuntu version it's built on), but pep257 was blocking making that possible last time so it's part of what needs to be done to update it :)

**Comment by airvzxf** [comment]
In the fix about macOS and Linux, I used Python 3.9, that's the reason I am asking because this change is done in the master repository. The pep257 is crashing if I replace by pydocstyle, and it is something that I am fixing right now. Only, to clarify.

**Python 3.9**

Linux
https://github.com/Pext/Pext/blob/master/.github/workflows/main.yml#L25
```yml
  linux:
    strategy:
      matrix:
        PEXT_BUILD_PORTABLE: [0, 1]
        OPERATIVE_SYSTEM: [ubuntu-18.04]
        PYTHON_VERSION: ["3.9"]
      ...
    steps:
      ...
      - name: Set up
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
```

macOS
https://github.com/Pext/Pext/blob/master/.github/workflows/main.yml#L60
```yml
  osx:
    strategy:
      matrix:
        PEXT_BUILD_PORTABLE: [0]
        OPERATIVE_SYSTEM: [macos-latest]
        PYTHON_VERSION: ["3.9"]
      ...
    steps:
      ...
      - name: Set up
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
```
